#!/bin/bash

set -euo pipefail

readonly dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority="${dir}/../certificates/ca.pem" \
    --embed-certs=true \
    --server=https://192.168.121.10:6443 \
    --kubeconfig="${dir}/../config/worker.kubeconfig"

kubectl config set-credentials system:node:worker \
    --client-certificate="${dir}/../certificates/worker.pem" \
    --client-key="${dir}/../certificates/worker-key.pem" \
    --embed-certs=true \
    --kubeconfig="${dir}/../config/worker.kubeconfig"

kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user=system:node:worker \
    --kubeconfig="${dir}/../config/worker.kubeconfig"

kubectl config use-context default --kubeconfig="${dir}/../config/worker.kubeconfig"
